### ISSUE TITLE
전기차 충전소 업데이트 및 데이터 저장 이슈

### ISSUE THREAD

**Issue by star-sil** [Charging-Life/BACK-END#12]
## 개요
전기자동차 충전소 정보 조회 api에서 받아온 모든 데이터를 DB에 저장하려 시도했다. 하지만 데이터가 너무많아 데이터를 저장하는데 많은 시간이 소요된다. 총 데이터 갯수는 143533개이고 저장하는데 30분 이상 걸리는 것을 확인했다.

## 이슈
 - 전기차 충전소는 지속적으로 추가되기에 주기적으로 api를 통해 정보를 받아와 추가된 충전소 정보를 저장해야한다.
 - 전기차 충전소의 상태 및 충전기 상태를 주기적으로 업데이트 해야한다. (사용가능한지, 언제부터 충전중인지....등등)

**Comment by kathyleesh** [comment]
https://spring.io/guides/gs/scheduling-tasks/
springframework의 scheduling을 사용하여 주기적으로 업데이트를 할 수 있게 합니다.
단 더 효율적인 업데이트를 위해 충전소의 경우에는 추가된 충전소를 찾아 업데이트를 할 수 있게 합니다.
scheduling 속성 중  매 같은 시간 업데이트가 가능한 @Scheduled(cron = "* * * * * *")와
일정 시간 마다 업데이트가 가능한  @Scheduled(fixedDelay = *)를 사용하여 기능을 개선 시킵니다.

**Comment by kathyleesh** [comment]
<img width="1169" alt="스크린샷 2022-10-07 오후 9 39 11" src="https://user-images.githubusercontent.com/90851865/194555759-f4d81999-8b0e-40ad-8eab-1ac71238a6e4.png">

**Comment by star-sil** [comment]
이슈가 해결된것 같아 닫겠습니다!! 추후에 해당 건에  대한 추가적인 이슈가 발생할경우 다시 열겠습니다.
